console.log(document.getElementById('string-3').innerText)
console.log(document.getElementById('string-5').innerText)
console.log(document.getElementById('string-2').innerText)
console.log(document.getElementById('string-6').innerText)
console.log(document.getElementById('string-4').innerText)
console.log(document.getElementById('string-1').innerText)